#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          mqtt-mpd-transport
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts mqtt-mpd-transport
# Description:       starts mqtt-mpd-transport
### END INIT INFO

. /lib/lsb/init-functions

d_start () {
        log_daemon_msg "Starting mqtt-mpd-transport"
        su autoc4 -c '/usr/bin/screen -d -m -S mpd-transport -- /bin/bash -c "cd /home/autoc4/logicer && /home/autoc4/.pyenv/shims/python mpd-transport.py"'
        log_end_msg $?
}

d_stop () {
        log_daemon_msg "Stopping mqtt-mpd-transport"
        pkill --list-full --full --exact "python mpd-transport.py"
        log_end_msg $?
}

case "$1" in

        start|stop)
                d_${1}
                ;;

        restart|reload|force-reload)
                        d_stop
                        d_start
                ;;

        force-stop)
               d_stop
                ;;

        status)
                ps aux | grep mpd-transport.py | grep -v grep
                ;;
        *)
                echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
                exit 1
                ;;
esac
exit 0
